function [P]=P_close(u,Vt,Ve,VL,data1,data2,data3,data4,data5,n,K)
P=0;
for i=1:n+1
  for  j=1:4
    P=K(1)*data1(j,i)*(Vt-Ve).^(i+u(1)-1)...
      +K(2)*data2(j,i)*(VL-Vt).^(i+u(2)-1)...
      +K(3)*data3(j,i)*(VL-Vt).^(i+u(3)-1)...
      +K(4)*data4(j,i)*(VL-Vt).^(i+u(4)-1)...
      +K(5)*data5(j,i)*(VL-Vt).^(i+u(5)-1)...
      +P;
   end
end
end