function [P]=P_q(u,Vt,Ve,VL,data1,data2,data3,data4,data5,n,K,q)
P=0;
for i=1:n+1
    P=K(1)*1/(i+u(1)+5-q)*data1(q,i)*(Vt-Ve)^(i+u(1)+5-q)...
        +K(2)*1/(i+u(2))*data2(q,i)*(VL-Vt)^(i+u(2))...
        +K(3)*1/(i+u(3))*data3(q,i)*(VL-Vt)^(i+u(3))...
        +K(4)*1/(i+u(4))*data4(q,i)*(VL-Vt)^(i+u(4))...
        +K(5)*1/(i+u(5))*data5(q,i)*(VL-Vt)^(i+u(5))+P;
end
end